name: portfolio_app
description: My Flutter portfolio app

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
